
import type { Metadata } from "next";
import { ClerkProvider } from '@clerk/nextjs'

import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import { Toaster } from "@/components/ui/toaster";
import DesignerContextProvider from "@/context/DesignerContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <DesignerContextProvider>
      <html lang="tr">
      <body className={inter.className}  suppressHydrationWarning={true}>
        <ThemeProvider
         attribute="class"
         defaultTheme="system"
         enableSystem
         disableTransitionOnChange
        >
          {children}
        <Toaster />
        </ThemeProvider>
        </body>
    </html>
      </DesignerContextProvider>
 
    </ClerkProvider>

  );
}
